# Example workflow for using Intellipulse Action
# Copy this file to your repository's .github/workflows/ directory

name: Intellipulse AI Response

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  intellipulse-response:
    runs-on: ubuntu-latest
    # Only respond to issues and issue comments
    if: github.event_name == 'issues' || github.event_name == 'issue_comment'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Intellipulse Action
        uses: your-username/intellipulse-action@main  # Replace with your repository
        with:
          intellipulse-action-key: ${{ secrets.INTELLIPULSE_ACTION_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
