name: Test Intellipulse Action

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, edited]

jobs:
  test:
    permissions:
      issues: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    # Only run on issues and issue comments, not on PRs to avoid unnecessary runs
    if: github.event_name == 'issues' || github.event_name == 'issue_comment'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Intellipulse Action
        id: intellipulse_action
        uses: ./
        with:
          intellipulse-action-key: ${{ secrets.INTELLIPULSE_ACTION_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check output
        run: "echo 'Intellipulse summary: ${{ steps.intellipulse_action.outputs.summary }}'"